//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Master_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Master_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Insurance.Resources.Master_en", typeof(Master_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select age.
        /// </summary>
        public static string AgeList {
            get {
                return ResourceManager.GetString("AgeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the checkbox.
        /// </summary>
        public static string AgreeCheckBox {
            get {
                return ResourceManager.GetString("AgreeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Quote.
        /// </summary>
        public static string BtnGetQuotes {
            get {
                return ResourceManager.GetString("BtnGetQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to log in.
        /// </summary>
        public static string ClickhereLogIn {
            get {
                return ResourceManager.GetString("ClickhereLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with us.
        /// </summary>
        public static string ConnectWithUs {
            get {
                return ResourceManager.GetString("ConnectWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string Contact_CallUs {
            get {
                return ResourceManager.GetString("Contact_CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Contact_Comment {
            get {
                return ResourceManager.GetString("Contact_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face any problem? .
        /// </summary>
        public static string Contact_FaceAnyProblem {
            get {
                return ResourceManager.GetString("Contact_FaceAnyProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Us at.
        /// </summary>
        public static string Contact_FindUsAt {
            get {
                return ResourceManager.GetString("Contact_FindUsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Contact_Name {
            get {
                return ResourceManager.GetString("Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a Mail.
        /// </summary>
        public static string Contact_SendEmail {
            get {
                return ResourceManager.GetString("Contact_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Contact_Submit {
            get {
                return ResourceManager.GetString("Contact_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inform us.
        /// </summary>
        public static string ContactUs_InformUs {
            get {
                return ResourceManager.GetString("ContactUs_InformUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment field is required.
        /// </summary>
        public static string ContactUsCommentRequired {
            get {
                return ResourceManager.GetString("ContactUsCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field is required.
        /// </summary>
        public static string ContactUsNameRequired {
            get {
                return ResourceManager.GetString("ContactUsNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request submitted sucessfully. We will contact you soon..
        /// </summary>
        public static string ContactUsSuccessMessage {
            get {
                return ResourceManager.GetString("ContactUsSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Insurance.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddress field is required.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-id is not correct , please check your email-id..
        /// </summary>
        public static string EmailLinkNotCorrect {
            get {
                return ResourceManager.GetString("EmailLinkNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string EmailLinkSent {
            get {
                return ResourceManager.GetString("EmailLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname field is required.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a Free Insurance Quote.
        /// </summary>
        public static string GetaFreeInsuranceQuote {
            get {
                return ResourceManager.GetString("GetaFreeInsuranceQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string HouseHold_Apartment {
            get {
                return ResourceManager.GetString("HouseHold_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string HouseHold_City {
            get {
                return ResourceManager.GetString("HouseHold_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condo.
        /// </summary>
        public static string HouseHold_Condo {
            get {
                return ResourceManager.GetString("HouseHold_Condo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter ID.
        /// </summary>
        public static string HouseHold_EnterID {
            get {
                return ResourceManager.GetString("HouseHold_EnterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your location.
        /// </summary>
        public static string HouseHold_EnterLocation {
            get {
                return ResourceManager.GetString("HouseHold_EnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sum insured.
        /// </summary>
        public static string HouseHold_EnterSumAssured {
            get {
                return ResourceManager.GetString("HouseHold_EnterSumAssured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Quotations.
        /// </summary>
        public static string HouseHold_GetQuotation {
            get {
                return ResourceManager.GetString("HouseHold_GetQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string HouseHold_House {
            get {
                return ResourceManager.GetString("HouseHold_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to grant the right to inquire.
        /// </summary>
        public static string HouseHold_IAgreeToGrant {
            get {
                return ResourceManager.GetString("HouseHold_IAgreeToGrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string HouseHold_Id {
            get {
                return ResourceManager.GetString("HouseHold_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string HouseHold_Location {
            get {
                return ResourceManager.GetString("HouseHold_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string HouseHold_Other {
            get {
                return ResourceManager.GetString("HouseHold_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string HouseHold_Rental {
            get {
                return ResourceManager.GetString("HouseHold_Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string HouseHold_StartDate {
            get {
                return ResourceManager.GetString("HouseHold_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string HouseHold_State {
            get {
                return ResourceManager.GetString("HouseHold_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum Insured.
        /// </summary>
        public static string HouseHold_SumInsured {
            get {
                return ResourceManager.GetString("HouseHold_SumInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your home.
        /// </summary>
        public static string HouseHold_TellUsAboutYourHome {
            get {
                return ResourceManager.GetString("HouseHold_TellUsAboutYourHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of coverage.
        /// </summary>
        public static string HouseHold_TypeOfCoverage {
            get {
                return ResourceManager.GetString("HouseHold_TypeOfCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the address you&apos;d like to ensure?.
        /// </summary>
        public static string HouseHold_WhatTheaddressYouLikeToEnsure {
            get {
                return ResourceManager.GetString("HouseHold_WhatTheaddressYouLikeToEnsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string HouseHold_ZipCode {
            get {
                return ResourceManager.GetString("HouseHold_ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to the terms and conditions of the company.
        /// </summary>
        public static string IAgreeToTheTerms {
            get {
                return ResourceManager.GetString("IAgreeToTheTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured national ID/Iqama/company.
        /// </summary>
        public static string IDNumber {
            get {
                return ResourceManager.GetString("IDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Hold.
        /// </summary>
        public static string InsHouseHold {
            get {
                return ResourceManager.GetString("InsHouseHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life &amp; Savings.
        /// </summary>
        public static string InsLifeAndSavings {
            get {
                return ResourceManager.GetString("InsLifeAndSavings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string InsMedical {
            get {
                return ResourceManager.GetString("InsMedical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Malpractice.
        /// </summary>
        public static string InsMedicalMalpractice {
            get {
                return ResourceManager.GetString("InsMedicalMalpractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        public static string InsTravel {
            get {
                return ResourceManager.GetString("InsTravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select insurance.
        /// </summary>
        public static string InsuraceList {
            get {
                return ResourceManager.GetString("InsuraceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quotes submitted successfully. We will reach you soon..
        /// </summary>
        public static string InsuranceSubmittedQuote {
            get {
                return ResourceManager.GetString("InsuranceSubmittedQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle insurance.
        /// </summary>
        public static string InsVehicleinsurance {
            get {
                return ResourceManager.GetString("InsVehicleinsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt or your account has been deleted..
        /// </summary>
        public static string Invalidloginattemptoryouraccount {
            get {
                return ResourceManager.GetString("Invalidloginattemptoryouraccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lang.en.js.
        /// </summary>
        public static string LangJs {
            get {
                return ResourceManager.GetString("LangJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName field is required.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance.
        /// </summary>
        public static string LayoutTitle {
            get {
                return ResourceManager.GetString("LayoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual Income.
        /// </summary>
        public static string Life_AnualIncome {
            get {
                return ResourceManager.GetString("Life_AnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit of Coverage.
        /// </summary>
        public static string Life_LimitOfCoverage {
            get {
                return ResourceManager.GetString("Life_LimitOfCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tobacco/Nicotine.
        /// </summary>
        public static string Life_SelectTobaccoNicotine {
            get {
                return ResourceManager.GetString("Life_SelectTobaccoNicotine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date of Insurance.
        /// </summary>
        public static string LIfe_StartDateofInsurance {
            get {
                return ResourceManager.GetString("LIfe_StartDateofInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about yourself.
        /// </summary>
        public static string Life_TellUsAboutYourself {
            get {
                return ResourceManager.GetString("Life_TellUsAboutYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Insurance Coverage.
        /// </summary>
        public static string Medical_SelectTypeOfInsuranceCoverage {
            get {
                return ResourceManager.GetString("Medical_SelectTypeOfInsuranceCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Insurance Coverage.
        /// </summary>
        public static string Medical_TypeOfInsuranceCoverage {
            get {
                return ResourceManager.GetString("Medical_TypeOfInsuranceCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Medicle_Age {
            get {
                return ResourceManager.GetString("Medicle_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Medicle_Personal_Information {
            get {
                return ResourceManager.GetString("Medicle_Personal Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about yourself.
        /// </summary>
        public static string Medicle_TellUsAboutYourself {
            get {
                return ResourceManager.GetString("Medicle_TellUsAboutYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit of Liability.
        /// </summary>
        public static string MedicleMalpractice_LimitOfLiability {
            get {
                return ResourceManager.GetString("MedicleMalpractice_LimitOfLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Family.
        /// </summary>
        public static string MedicleMalpractice_MyFamily {
            get {
                return ResourceManager.GetString("MedicleMalpractice_MyFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Parents.
        /// </summary>
        public static string MedicleMalpractice_MyParents {
            get {
                return ResourceManager.GetString("MedicleMalpractice_MyParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myself.
        /// </summary>
        public static string MedicleMalpractice_Myself {
            get {
                return ResourceManager.GetString("MedicleMalpractice_Myself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Insurance for.
        /// </summary>
        public static string MedicleMalPractice_NeedInsuranceFor {
            get {
                return ResourceManager.GetString("MedicleMalPractice_NeedInsuranceFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Limit of Liability.
        /// </summary>
        public static string MedicleMalpractice_SelectLimitOfLiability {
            get {
                return ResourceManager.GetString("MedicleMalpractice_SelectLimitOfLiability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Speciality.
        /// </summary>
        public static string MedicleMalpractice_SelectSpeciality {
            get {
                return ResourceManager.GetString("MedicleMalpractice_SelectSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string MedicleMalpractice_Speciality {
            get {
                return ResourceManager.GetString("MedicleMalpractice_Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date of Insurance.
        /// </summary>
        public static string MedicleMalpractice_StartDateofInsurance {
            get {
                return ResourceManager.GetString("MedicleMalpractice_StartDateofInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the address you&apos;d like to ensure?.
        /// </summary>
        public static string MedicleMalPractice_WhattheaddressYouLikeToEnsure {
            get {
                return ResourceManager.GetString("MedicleMalPractice_WhattheaddressYouLikeToEnsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string MenuAboutUs {
            get {
                return ResourceManager.GetString("MenuAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string MenuContactUs {
            get {
                return ResourceManager.GetString("MenuContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string MenuPrivacyPolicy {
            get {
                return ResourceManager.GetString("MenuPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string MenuTermsConditions {
            get {
                return ResourceManager.GetString("MenuTermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Insurance.
        /// </summary>
        public static string NewInsurance {
            get {
                return ResourceManager.GetString("NewInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Partner.
        /// </summary>
        public static string OurPartner {
            get {
                return ResourceManager.GetString("OurPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password field is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string PHolderEmail {
            get {
                return ResourceManager.GetString("PHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string PHolderFirstName {
            get {
                return ResourceManager.GetString("PHolderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string PHolderLastName {
            get {
                return ResourceManager.GetString("PHolderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PHolderPhoneNumber {
            get {
                return ResourceManager.GetString("PHolderPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Age.
        /// </summary>
        public static string PHolderYourAge {
            get {
                return ResourceManager.GetString("PHolderYourAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber field is required..
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Insurance.
        /// </summary>
        public static string PurposeofInsurance {
            get {
                return ResourceManager.GetString("PurposeofInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Quotes {
            get {
                return ResourceManager.GetString("Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request quote submitted sucessfully. We will contact you soon..
        /// </summary>
        public static string QuoteSuccessMessage {
            get {
                return ResourceManager.GetString("QuoteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid.
        /// </summary>
        public static string RegEmail {
            get {
                return ResourceManager.GetString("RegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have account?.
        /// </summary>
        public static string Regis_AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("Regis_AlreadyHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Regis_ConfirmPassword {
            get {
                return ResourceManager.GetString("Regis_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Regis_Login {
            get {
                return ResourceManager.GetString("Regis_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Regis_Registration {
            get {
                return ResourceManager.GetString("Regis_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        public static string Regis_Signup {
            get {
                return ResourceManager.GetString("Regis_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string Regis_ThePasswordConfirmationPassword {
            get {
                return ResourceManager.GetString("Regis_ThePasswordConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string ResetYourPpassword {
            get {
                return ResourceManager.GetString("ResetYourPpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is Required.
        /// </summary>
        public static string ReuiredField {
            get {
                return ResourceManager.GetString("ReuiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string SelectDropdownlist {
            get {
                return ResourceManager.GetString("SelectDropdownlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 2.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEP 3.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select terms conditions.
        /// </summary>
        public static string TermsCondition {
            get {
                return ResourceManager.GetString("TermsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer of ownership.
        /// </summary>
        public static string TransferOfOwnership {
            get {
                return ResourceManager.GetString("TransferOfOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Travel_Destination {
            get {
                return ResourceManager.GetString("Travel_Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Country.
        /// </summary>
        public static string Travel_DestinationCountry {
            get {
                return ResourceManager.GetString("Travel_DestinationCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Travel_Duration {
            get {
                return ResourceManager.GetString("Travel_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter destination.
        /// </summary>
        public static string Travel_EnterDestination {
            get {
                return ResourceManager.GetString("Travel_EnterDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Duration.
        /// </summary>
        public static string Travel_EnterDuration {
            get {
                return ResourceManager.GetString("Travel_EnterDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your passport number.
        /// </summary>
        public static string Travel_EnterPassportNumber {
            get {
                return ResourceManager.GetString("Travel_EnterPassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gender.
        /// </summary>
        public static string Travel_Gender {
            get {
                return ResourceManager.GetString("Travel_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Number.
        /// </summary>
        public static string Travel_PassportNumber {
            get {
                return ResourceManager.GetString("Travel_PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Details.
        /// </summary>
        public static string Travel_PersonalDetails {
            get {
                return ResourceManager.GetString("Travel_PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us about your Trip.
        /// </summary>
        public static string Travel_TellUsAboutYourTrip {
            get {
                return ResourceManager.GetString("Travel_TellUsAboutYourTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Date From.
        /// </summary>
        public static string Travel_TripDateFrom {
            get {
                return ResourceManager.GetString("Travel_TripDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Date To.
        /// </summary>
        public static string Travel_TripDateTo {
            get {
                return ResourceManager.GetString("Travel_TripDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Trravel_Age {
            get {
                return ResourceManager.GetString("Trravel_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string UserLogin_DontHaveAccount {
            get {
                return ResourceManager.GetString("UserLogin_DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string UserLogin_ForgotPassword {
            get {
                return ResourceManager.GetString("UserLogin_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string UserLogin_LogIn {
            get {
                return ResourceManager.GetString("UserLogin_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string UserLogin_Password {
            get {
                return ResourceManager.GetString("UserLogin_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember password.
        /// </summary>
        public static string UserLogin_RememberPassword {
            get {
                return ResourceManager.GetString("UserLogin_RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string UserLogin_SignIn {
            get {
                return ResourceManager.GetString("UserLogin_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup.
        /// </summary>
        public static string UserLogin_Signup {
            get {
                return ResourceManager.GetString("UserLogin_Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserLogin_Username {
            get {
                return ResourceManager.GetString("UserLogin_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Card.
        /// </summary>
        public static string Vechicle_CustomCard {
            get {
                return ResourceManager.GetString("Vechicle_CustomCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        public static string Vechicle_SequenceNumber {
            get {
                return ResourceManager.GetString("Vechicle_SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an insurance?.
        /// </summary>
        public static string Vehicle_DoYouAlreadyHaveAnInsurance {
            get {
                return ResourceManager.GetString("Vehicle_DoYouAlreadyHaveAnInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter registration type number.
        /// </summary>
        public static string Vehicle_EnterRegistrationType {
            get {
                return ResourceManager.GetString("Vehicle_EnterRegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Insurance.
        /// </summary>
        public static string Vehicle_NewInsurance {
            get {
                return ResourceManager.GetString("Vehicle_NewInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string Vehicle_PersonalInformation {
            get {
                return ResourceManager.GetString("Vehicle_PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Of Insurance.
        /// </summary>
        public static string Vehicle_PuposeOfInsurance {
            get {
                return ResourceManager.GetString("Vehicle_PuposeOfInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Type.
        /// </summary>
        public static string Vehicle_RegistrationType {
            get {
                return ResourceManager.GetString("Vehicle_RegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell Us about your Vehicle.
        /// </summary>
        public static string Vehicle_TellUsAboutYourVehicle {
            get {
                return ResourceManager.GetString("Vehicle_TellUsAboutYourVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Ownership.
        /// </summary>
        public static string Vehicle_TransferOwnership {
            get {
                return ResourceManager.GetString("Vehicle_TransferOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Brand.
        /// </summary>
        public static string Vehicle_VehicleBrand {
            get {
                return ResourceManager.GetString("Vehicle_VehicleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model.
        /// </summary>
        public static string Vehicle_VehicleModel {
            get {
                return ResourceManager.GetString("Vehicle_VehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle registration number.
        /// </summary>
        public static string Vehicle_VehicleRegistrationNumber {
            get {
                return ResourceManager.GetString("Vehicle_VehicleRegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to log in here..
        /// </summary>
        public static string YouAreNotAllowedToLogInHere {
            get {
                return ResourceManager.GetString("YouAreNotAllowedToLogInHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked. Kindly contact to administrator..
        /// </summary>
        public static string YourAccountHasBeenblocked {
            get {
                return ResourceManager.GetString("YourAccountHasBeenblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created successfully..
        /// </summary>
        public static string YourAccountHasBeenCreatedSuccessfully {
            get {
                return ResourceManager.GetString("YourAccountHasBeenCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
